# .github/languages.yml

- name: "Hip+"
  color: "FF0000"
  secondary_color: "#8000FF"
  logo: "url/to/hipplus-logo.png"
  extensions:
    - ".hip+"
  interpreters:
    - "hipplus-interpreter"
  ace_mode: "text"
  tm_scope: "source.hipplus"
  wrap: true
  aliases:
    - "hipplus"
  group: "Other"
