# .github/languages.yml

- name: "Hip+"
  color: "#8000FF"
  secondary_color: "#8000FF"
  logo: "url/to/hipplus-logo.png"
  extensions:
    - ".hipplus"
  interpreters:
    - "hipplus-interpreter"
  ace_mode: "code"
  tm_scope: "source.hipplus"
  wrap: true
  aliases:
    - "hipplus"
  group: "Other"
