name: Publish and Build hip+

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Publish hip+
      run: |
        # Example for publishing and building hip+ using npm package manager
- name: Publish and Build hip+
  run: |
    npm install -g hipplus-cli
    hipplus build
    hipplus publish --token ${{ secrets.YOUR_TOKEN }}
- name: Notify on Completion
  run: echo "hip+ has been successfully published and built."
 
